'\" t
.\"     Title: bitmath
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 07/17/2016
.\"    Manual: python-bitmath
.\"    Source: bitmath 1.3.1
.\"  Language: English
.\"
.TH "BITMATH" "1" "07/17/2016" "bitmath 1\&.3\&.1" "python\-bitmath"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bitmath \- command line utility for converting between prefix units
.SH "SYNOPSIS"
.sp
bitmath [\-\-from\-stdin] [\-f IN_UNIT] [\-t OUT_UNIT] SIZE \&...
.SH "DESCRIPTION"
.sp
Run it, give a number as the last parameter\&. Say what units you\(cqre giving/wanting, or not\&.
.SH "OPTIONS"
.PP
\fB\-\-from\-stdin\fR
.RS 4
Reads number from stdin rather than the cli\&.
.RE
.PP
\fB\-f\fR \fIUNIT\fR, \fB\-\-from\fR \fIUNIT\fR
.RS 4
The unit you are converting from\&. Default is
\fBByte\fR\&.
.RE
.PP
\fB\-t\fR \fIUNIT, \fR\fI\fB\-\-to\fR\fR\fI \*(AqUNIT\fR
.RS 4
The unit you are converting to\&. The default is
\fBauto\-selected\fR
for best human\-readability\&.
.RE
.SH "AUTHOR"
.sp
Tim Bielawa <timbielawa@gmail\&.com>
.sp
For a complete list of contributors, please visit the GitHub charts page\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2014\-2016, Tim Bielawa\&.
.sp
bitmath is released under the terms of the "MIT" License\&.
.SH "SEE ALSO"
.sp
\fBunits\fR(7)
.sp
\fBThe bitmath GitHub Project\fR \(em https://github\&.com/tbielawa/bitmath
.sp
\fBThe bitmath Documentation\fR \(em https://bitmath\&.readthedocs\&.org
