name: Makefile CI

on:
  push:
    branches: [ "master", "2023-01-26-no-more-py2" ]
  pull_request:
    branches: [ "master", "2023-01-26-no-more-py2" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

    - name: Run unittests
      run: make ci
